development: &global_settings
  database: '#tcc-development'
  host: 127.0.0.1
  port: 27017

test:
  database: '#tcc-test'
  <<: *global_settings

production:
  host: hostname
  database: '#tcc-production'
  username: username
  password: password
  <<: *global_settings